apiVersion: kubechain.humanlayer.dev/v1alpha1
kind: Agent
metadata:
  name: humanlayer-agent
spec:
  llmRef:
    name: gpt-4o
  tools:
    - name: humanlayer-function-call
  system: |
    You are a calculator agent that can perform mathematical operations.
    You have access to the 'humanlayer-function-call' tool which adds two numbers together. You should never infer your own reasoing, but call that function.
status:
  ready: true
  status: "Ready"
  statusDetail: "Agent is configured and ready"
  validTools:
    - kind: "Tool"
      name: "humanlayer-function-call"